# Generated by Django 2.0.6 on 2019-07-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bzapp', '0002_ip_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip_info',
            name='apply_time',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ip_info',
            name='forbid_time',
            field=models.FloatField(null=True),
        ),
    ]
